@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Your Menu's QR Code</h1>
    </div>

    <div class="card">
        <div class="card-body text-center">
            <h5 class="card-title">Scan to View Live Menu</h5>
            <p class="card-text">
                Use your phone's camera to scan the code below, or download it to use in your print materials.
            </p>

            <!-- QR Code generated by the package -->
            <div class="my-4" id="qr-code-container">
                {!! QrCode::size(300)->generate($url) !!}
            </div>

            <p class="text-muted">This QR code points to the following URL:</p>
            <p><strong><a href="{{ $url }}" target="_blank">{{ $url }}</a></strong></p>

            <hr>

            <h5 class="mt-4">Download QR Code</h5>
            <p>For best quality, download the SVG format for printing.</p>

            <div class="btn-group" role="group" aria-label="Download formats">
                <a href="#" id="download-svg" class="btn btn-primary"><i class="fas fa-file-alt me-2"></i> Download as SVG</a>
                <a href="#" id="download-png" class="btn btn-secondary"><i class="fas fa-file-image me-2"></i> Download as PNG</a>
            </div>
        </div>
    </div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const qrContainer = document.getElementById('qr-code-container');
    const svgElement = qrContainer.querySelector('svg');

    // Function to trigger download
    function download(blob, filename) {
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }

    // Download as SVG
    document.getElementById('download-svg').addEventListener('click', function(e) {
        e.preventDefault();
        const svgData = new XMLSerializer().serializeToString(svgElement);
        const blob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
        download(blob, 'menu-qr-code.svg');
    });

    // Download as PNG
    document.getElementById('download-png').addEventListener('click', function(e) {
        e.preventDefault();
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        const svgData = new XMLSerializer().serializeToString(svgElement);
        const img = new Image();

        img.onload = function() {
            canvas.width = img.width;
            canvas.height = img.height;
            ctx.drawImage(img, 0, 0);
            canvas.toBlob(function(blob) {
                download(blob, 'menu-qr-code.png');
            });
        };
        img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
    });
});
</script>
@endsection